<div id="leftPane">
	<h1>Import Data</h1>
	<p>Select data to import</p>
	<ul id="dataMaintList">
		<li id="dmCust" class="dmEven" onclick="javascript:dmSel(this,'cust')">Members</li>
		<li id="dmStaff" class="dmOdd" onclick="javascript:dmSel(this,'staff')">Staff</li>
		<li id="dmOpro" class="dmEven" onclick="javascript:dmSel(this,'opro')">Other Professionals</li>
		<li id="dmSrvc" class="dmOdd" onclick="javascript:dmSel(this,'srvc')">Services</li>
		<li id="dmReltype" class="dmEven" onclick="javascript:dmSel(this,'reltype')">Relationships</li>
		<li id="dmCat" class="dmOdd" onclick="javascript:dmSel(this,'cat')">Categories</li>
	</ul>	
</div>
<div id="rightPane">
	<h1>Map your data fields</h1>
	<div id="impmap"><?= $this->form ?></div>
	<h1>Save/Retrieve import profile</h1>
	<div><?= $this->proform ?></div>
</div>
<div class="clear"></div>
<script type="text/javascript"><?php echo "var _lastSel='#dm{$this->tbl}'"; ?></script>
<div id="uiError" class="noshow" title="Error">
	<p id="errMsg"></p>
</div>
<div id="uiNotice" class="noshow" title="Notice">
	<p id="msg"></p>
</div>