	<h1>Import Data</h1>
	<p>Select data to import</p>
	<ul id="dataMaintList">
		<li id="dmCust" class="dmEven" onclick="javascript:dmSel(this,'cust')">Members</li>
		<li id="dmStaff" class="dmOdd" onclick="javascript:dmSel(this,'staff')">Staff</li>
		<li id="dmOpro" class="dmEven" onclick="javascript:dmSel(this,'opro')">Other Professionals</li>
		<li id="dmSrvc" class="dmOdd" onclick="javascript:dmSel(this,'srvc')">Services</li>
		<li id="dmReltype" class="dmEven" onclick="javascript:dmSel(this,'reltype')">Relationships</li>
		<li id="dmCat" class="dmOdd" onclick="javascript:dmSel(this,'cat')">Categories</li>
	</ul>	

