<div class="topPanel">
	<h1>Forgotten password</h1>
	<p>Please enter your details below and we will send a <em>new</em> password to the email address registered to that account.</p>
	<p><span class="icon tip"></span> Don't forget to change your password to a memorable one after you log in.</p>
</div>

<?=$this->form; ?>

<div class="clear"></div>

<?php if ($this->success===true) { ?>

	<div class="noshow">
		<div id="thankYouPopup" class="popup small">
			<h2>Check your email!</h2>
			<p></p>
			<div class="controls">
				<button type="button" class="button ok closePopup">Close</button>
			</div>
		</div>
	</div>

	<script type="text/javascript">
		$(document).ready(function(){
			//popup($('#thankYouPopup').parent().html());
			simplePopupMessage({title:'Check your email!',message:'Your new passsword has been sent to your email address.  When you get it, log back in and don\'t forget to change the password in your profile to something only you know.'});
		});
	</script>

<?php } ?>