	<ul id="dataMaintList">
	<?php 
		$rowClass = 'dmEven';
		$nav = new Zend_Navigation(new Zend_Config_Xml(ZF4_BASE_PATH . '/application/config/navigation.xml','main'));
		$subMenu = $nav->findOneBy('resource','default_usage_index');
		$acl = Application_Model_Acl::getACL();
		$user= new Application_Model_User(ZF4_User::getIdentity());
		$roles = $user->getRoles();
		foreach ($subMenu as $page) { 
			$parts = explode('_',$page->resource);
			$tag = $parts[2];
			$id = 'dm' . ucfirst($tag);
			$canSee = false;
			foreach ($roles as $role) {
				if ($acl->isAllowed($role,$page->resource)) {
					$canSee = true;
					break;
				}
			}
			if ($canSee) {
			?>
			<li id="<?= $id ?>" class="<?= $rowClass ?>" title="<?= $page->title ?>" onclick="javascript:dmSel(this,'<?= $tag ?>')"><?= $page->label?></li>
		<?php 
			$rowClass = ($rowClass == 'dmEven' ? 'dmOdd' : 'dmEven'); }
		}
	?>
	</ul>
