<h1>Your Services</h1>
<h2>For: <?= $this->userName ?></h2>
<p>Hover over a service name for more information. This will tell you the when, where and how much (if anything) it costs.</p>
<p>Family Map do not make any money on charges made by <?= $this->orgName?>, so you can be assured that any charges they make are directly related to the cost of providing the service.</p>
<p>For any services that a charge is made for, <?= $this->orgName?> will make arrangements with you personally for collection</p>
<p>In the other services section, if availability states that you should contact the service provider, 
this generally means that the service is open to you if there is a need for it.</p>
<div class="admin">
	<table width="80%">
		<tr>
			<td>Your Administrator is:</td>
			<td><?= $this->adminName ?></td>
		</tr>
		<tr>
			<td>Contact telephone:</td>
			<td><?= $this->adminTel ?></td>
		</tr>
	</table>
</div>
