<div id="panelLeft" >
	<h1>Credits</h1>
	<h2>Credit where credit is due</h2>
	<p>This website is possible due to the efforts of many people and organisations.  We'd like to extend our thanks to them here.</p>

	<br />
	<h2>Family Map Version</h2>
	<p>Version: <?= $this->verWLC ?></p>
<!--	<p>Revision: <?= $this->revision ?></p>
	<p>Last Change: <?= $this->lastChange ?></p> -->	
</div>
<div id='panelMid'>
	<h2>The people</h2>
	<dl>
		<dt>System Concept</dt>
		<dd>Julia Kitson</dd>
		<dt>Site Design and Software Engineering</dt>
		<dd>Ashley Kitson</dd>
	</dl>
</div>
<div id="panelRight">
	<h2>The organisations</h2>
	<dl>
		<dt>Original Funding</dt>
		<dd><a href="http://www.woodnewton.northants.sch.uk/home.htm" target="_blank">Woodnewton - a learning community</a></dd>
		<dt>Website Production</dt>
		<dd><a href="http://zf4.biz" target="_blank">ZF 4 Business Limited</a></dd>
		<dt>PHP Software Framework</dt>
		<dd><a href="http://framework.zend.com/" target="_blank">Zend Framework V<?= $this->verZF ?></a></dd>
		<dt>Javascript jQuery Library</dt>
		<dd><a href="http://jquery.com/" target="_blank">jQuery V<?= $this->verJQ ?></a></dd>
		<dt>Javascript jQuery UI Library</dt>
		<dd><a href="http://jqueryui.com/" target="_blank">jQuery UI V<?= $this->verJQUI ?></a></dd>
		<dt>Javascript jQGrid Library</dt>
		<dd><a href="http://www.trirand.com/blog/" target="_blank">jQGrid V<?= $this->verJQGrid ?></a></dd>
		<dt>Javascript Google Maps Library</dt>
		<dd><a href="http://code.google.com/apis/maps/documentation/javascript/" target="_blank">Google Maps V<?= $this->verGoogleMaps ?></a></dd>
		<dt>Google Maps API</dt>
		<dd><a href="http://code.google.com/apis/maps/documentation/mapsdata/" target="_blank">Google Data API V<?= $this->verGoogleAPI ?></a></dd>
		<dt>Google Markers Library</dt>
		<dd><a href="http://gmaps-utility-library.googlecode.com/svn/trunk/markermanager/1.1/docs/examples.html" target="_blank">Google MarkerManager V<?= $this->verMarker ?></a></dd>
		<dt>Google Map Tools (inspiration)</dt>
		<dd><a href="http://www.birdtheme.org/useful/v3tool.html" target="_blank">Kjell Scharning's Toolbox V<?= $this->verKjells ?></a></dd>
		<!--<dt>Intruder Detection Library</dt>
		<dd><a href="http://php-ids.org/" target="_blank">PHPIDS V<?= $this->verIDS ?></a></dd>-->
		<dt>Network graphing tool</dt>
		<dd><a href="http://asterisq.com/" target="_blank">*Asterisq</a></dd>
		<dt>System Stack</dt>
		<dd><a href="http://en.wikipedia.org/wiki/Linux" target="_blank">Linux</a>, <a href="http://en.wikipedia.org/wiki/Apache_HTTP_Server" target="_blank">Apache</a>. <a href="http://en.wikipedia.org/wiki/Mysql" target="_blank">MySql</a>, <a href="http://en.wikipedia.org/wiki/Php" target="_blank">PHP</a></dd>
		
	</dl>

</div>
<div class="clear"></div>