<?php if ($this->success===true) { ?>
	
	<div class="noshow">
		<div id="thankYouPopup" class="popup small">
			<h2>Done!</h2>
			<p>Your details have been saved successfully.</p>
			<div class="controls">
				<button type="button" class="button ok closePopup">Close</button>
			</div>
		</div>
	</div>
	
	<script type="text/javascript">
		$(document).ready(function(){
			popup($('#thankYouPopup').parent().html());
		});
	</script>
	
<?php } ?>

<h1>My Account</h1>
	
<p>You can use this form to change your user account details.</p>
<?php if (!$this->seeFooterLinks) { ?>
<p>Supplying your email address means that we can email a new password if you forget it!</p>
<?php } ?>
<p>When you have finished, click 'submit' to save your changes.</p>
<?= $this->form; ?>
<?php if (!$this->seeFooterLinks) { ?>
<div class="admin">
	<table width="80%">
		<tr>
			<td>Your Administrator is:</td>
			<td><?= $this->adminName ?></td>
		</tr>
		<tr>
			<td>Contact telephone:</td>
			<td><?= $this->adminTel ?></td>
		</tr>
	</table>
</div>
<?php } ?>
<div class="clear"></div>

