<div class="topPanel">
	<h1>Data Hub Users</h1>
	<div class="topControls">
		<button type="button" class="button add" id="btn-addRow">Add user</button>
		<button type="button" class="button edit disabled" disabled="disabled" id="btn-editRow">Edit selected user</button>
		<button type="button" class="button delete disabled" disabled="disabled" id="btn-deleteRow">Delete selected user</button>
		<button type="button" class="button search" id="btn-search">Search for a user</button>
	</div>
</div>
<table id="userList"></table>
<div id="userListPager"></div>
