<h1>Welcome</h1>
<p>This is the demonstration system for Family Map from ZF 4 Business Limited</p>
<p>Please feel free to explore the system.  Your user privilege is that of an administrator.  This means that you can do just about anything with the system.  However, to access the documentation, you will need to use a separate username and password.</p>

<p> The documentation signon details are:
<dl>
	<dt>Username</dt>
	<dd>demoadmin</dd>
	<dt>Password</dt>
	<dd>demoadmin</dd>
</dl>
</p>

<p>The system is reset every hour. This means that any data you input will be cleared out.  This allows us to give everyone who wants, a clear run at the system without cluttering it up unnecessarily.  The user id you have been allocated will expire in 14 days.</p>